FROM node:22-alpine

WORKDIR /API

COPY package*.json ./

RUN npm install

COPY . .
RUN npx prisma generate
RUN npm run build || cat /root/.npm/_logs/* || true

EXPOSE 3000

CMD ["node", "dist/prisma/config/emailConsumer.js"]

