#version: "3.8"

services:
  api:
    build: .
    container_name: api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

    command: > 
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run build &&
      npm run start"
    environment:
    - DATABSE_URL=postgresql://seeisa:karabo@db:5432/top_user
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6380"

  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: seeisa
      POSTGRES_PASSWORD: karabo
      POSTGRES_DB: top_user
    ports:
      - "5432:5432"

