name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: seeisa
          POSTGRES_PASSWORD: karabo
          POSTGRES_DB: top_user_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://seeisa:karabo@localhost:5432/top_user_test
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://localhost

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          check-latest: true
          
      - name: Print environment variable
        run: |
           echo "REDIS_URL=$REDIS_URL"
           echo "REDIS_HOST=$REDIS_HOST"
           echo "REDIS_PORT=$REDIS_PORT"
           echo "DATABASE_URL=$DATABASE_URL"


      - name:  Install dependencies
        run: npm ci

      - name: 🔄 Generate Prisma Client
        run: npx prisma generate
        
      - name: Wait for Postgres
        run: |
         for i in {1..10}; do
         if pg_isready -U seeisa -d top_user_test -h localhost -p 5432; then
         break
         fi
         sleep 2
         done
        

      - name: 🧱 Run Migrations
        run: npx prisma migrate deploy
              
      - name: Seed database
        env:
          DATABASE_URL: postgresql://seeisa:karabo@localhost:5432/top_user_test
        run: npx prisma db seed

      - name: List DB tables
        run: psql $DATABASE_URL -c "\dt"

      - name: Reset DB
        run: npx prisma migrate reset --force


      - name: 🧪 Run Tests
        run: npm run test
